name: CI

on:
  create:
    tags:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - uses: actions/checkout@v1
      - name: install tools
        run: pip3 install flake8==3.7.8
      - run: flake8
  build:
    name: ${{ matrix.config }}, ${{ matrix.preset }}, ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      CMAKE_GENERATOR: Ninja
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            preset: gnu
            config: Release
          - os: ubuntu-latest
            preset: asan
            config: Debug
          - os: ubuntu-latest
            preset: asan
            config: Release
          - os: ubuntu-latest
            preset: ubsan
            config: Debug
          - os: ubuntu-latest
            preset: ubsan
            config: Release
          - os: macos-latest
            preset: clang
            config: Release
          - os: windows-latest
            preset: msvc
            config: Release
    steps:
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: seanmiddleditch/gha-setup-ninja@master
      - uses: jwlawson/actions-setup-cmake@v1.8
        with:
          cmake-version: 3.x
      - name: GTest build
        run: |
          cmake -S third_party/gtest -B build/gtest -DCMAKE_BUILD_TYPE=Release
          cmake --build build/gtest
          cmake --install build/gtest --prefix _install
      - name: Configure WABT
        run: >
          cmake --preset=${{ matrix.preset }} -DCMAKE_BUILD_TYPE=${{ matrix.config }}
          -DGTest_DIR=${{ github.workspace }}/_install/lib/cmake/GTest
      - name: Build WABT
        run: cmake --build out
      - name: Run tests
        run: ctest --output-on-failure -LE slow
        working-directory: out

  emscripten:
    name: emscripten
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: mymindstorm/setup-emsdk@v9
        with:
          version: 1.39.10
          actions-cache-folder: 'emsdk-cache'
      - uses: seanmiddleditch/gha-setup-ninja@master
      - uses: jwlawson/actions-setup-cmake@v1.8
        with:
          cmake-version: 3.x
      - name: Print emcc version
        run: echo $EMSDK && emcc -v
      - name: GTest build
        run: |
          emcmake cmake -S third_party/gtest -B build/gtest -DCMAKE_BUILD_TYPE=Release
          cmake --build build/gtest
          cmake --install build/gtest --prefix _install
      - name: CMake configure
        run: >
          cmake --preset=emscripten -DCMAKE_BUILD_TYPE=Release -DCMAKE_BUILD_TYPE=Release
          -DGTest_DIR=${{ github.workspace }}/_install/lib/cmake/GTest
      - name: CMake build
        run: cmake --build out -- -v
